define z = Character("Zee", color="#c8ffc8")
define m = Character("Me", color="#FFBB70")
define mc       = Character("Totok", color="#c8ffc8")
define aangs    = Character("???", color="#ffffff")
define aang     = Character("Aang", color="#FFBB70")
define penjual  = Character("Bapak Penjual", color="#7ABA78")
define kg       = Character("Kakek Gamelan", color="#7ABA78")
define pu       = Character("Pak Ustad", color="#7ABA78")
define ma       = Character("Totok & Aang", color="#7ABA78")
define pb       = Character("Panitia beginner", color="#7ABA78")
define su       = Character("Sutrisno", color="#7ABA78")